# Generated by Django 6.0.1 on 2026-01-28 19:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The text that appears in the badge (e.g., 'Handcrafted')",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "alt_text",
                    models.CharField(default="Artisan Object", max_length=200),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
