# Generated by Django 6.0.1 on 2026-01-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_ordertracking_ordertrackingevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
