# Generated by Django 6.0.2 on 2026-02-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="paypal_capture_id",
            new_name="provider_order_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="paypal_order_id",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_provider",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_capture_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
    class Migration(migrations.Migration):

        dependencies = [
            ("orders", "0004_alter_order_email"),
        ]

        operations = [
            # 1. Rename paypal_order_id → provider_order_id
            migrations.RenameField(
                model_name="order",
                old_name="paypal_order_id",
                new_name="provider_order_id",
            ),
            # 2. Rename paypal_capture_id → provider_capture_id
            migrations.RenameField(
                model_name="order",
                old_name="paypal_capture_id",
                new_name="provider_capture_id",
            ),
            # 3. Add the new payment_provider field
            migrations.AddField(
                model_name="order",
                name="payment_provider",
                field=models.CharField(
                    blank=True, db_index=True, default="", max_length=50
                ),
                preserve_default=False,
            ),
        ]