# Generated by Django 6.0.2 on 2026-02-12 10:48

import backend.apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", backend.apps.accounts.models.UserManager()),
            ],
        ),
    ]
