# Generated by Django 6.0.1 on 2026-01-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="stripe_payment_intent",
        ),
        migrations.RemoveField(
            model_name="order",
            name="stripe_session_id",
        ),
        migrations.AddField(
            model_name="order",
            name="paypal_capture_id",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paypal_order_id",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
