# Generated by Django 6.0.1 on 2026-01-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_alt",
            field=models.CharField(
                default=2,
                help_text="Brief description of the image for screen readers (e.g., 'Blue ceramic vase on oak table').",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
